In [1]:
import polars as pl

In [9]:
data=pl.read_csv('tips_atualizado.csv')
data.head(3)

shape: (3, 6)
┌────────────┬──────┬─────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ dessert ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---     ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str     ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪═════════╪═════╪════════╪══════╡
│ 16.99      ┆ 1.01 ┆ No      ┆ Sun ┆ Dinner ┆ 2    │
│ 10.34      ┆ 1.66 ┆ No      ┆ Sun ┆ Dinner ┆ 3    │
│ 21.01      ┆ 3.5  ┆ No      ┆ Sun ┆ Dinner ┆ 3    │
└────────────┴──────┴─────────┴─────┴────────┴──────┘

In [ ]:
# Limpando e tratando os dados

# Modificando a nomenclatura das colunas para [PT-BR]
columns={
    'total_bill':'conta_total',
    'tip':'gorjeta',
    'dessert':'sobremesa',
    'day':'dia';
    'time':'horario',
    'size':'clientes'
}
data.columns=columns

# Transformando valores sobremesa
data[data['dia']== "No"] = False
data[data['dia']== "Yes"] = True

# Modificando valores horario
data.groupby(['time'])
data[data['horario']=='Dinner'] = 'Janta'
data[data['horario']=='Lunch'] = 'Almoco'

# Modificando valores dia
data.groupby(['day'])

#Checando dados faltantes