# Relatório de Análise VII

## Criando Agrupamentos

In [8]:
import pandas as pd

In [9]:
dados= pd.read_csv('dados/aluguel_residencial.csv', sep=';')

In [10]:
dados.head(4)

,Unnamed: 0,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
2,2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0

In [11]:
#bairros= ['Barra da Tijuca', 'Copacabana','Ipanema','Leblon','Botafogo','Tijuca']
#new_data=dados[dados['Bairro'].isin(bairros)]

In [24]:
grupo_bairros= dados.groupby('Bairro')
#type(grupo_bairros)

In [25]:
#grupo_bairros.groups

In [26]:
for bairro, data in grupo_bairros:
    print('Bairro: ', bairro)
    print('Média: ', data.Valor.mean().round(4))
    print()
    #print(dados)

Bairro:  Abolição
Média:  1195.3333

Bairro:  Alto da Boa Vista
Média:  3966.6667

Bairro:  Anchieta
Média:  875.0

Bairro:  Andaraí
Média:  1464.7113

Bairro:  Anil
Média:  2048.8732

Bairro:  Arpoador
Média:  12923.9167

Bairro:  Bancários
Média:  1825.0

Bairro:  Bangu
Média:  1016.0

Bairro:  Barra da Tijuca
Média:  7069.5529

Bairro:  Barra de Guaratiba
Média:  5550.0

Bairro:  Benfica
Média:  996.0

Bairro:  Bento Ribeiro
Média:  1030.8696

Bairro:  Bonsucesso
Média:  1225.9322

Bairro:  Botafogo
Média:  8791.8282

Bairro:  Braz de Pina
Média:  1115.0

Bairro:  Cachambi
Média:  1157.1742

Bairro:  Cachamorra
Média:  3000.0

Bairro:  Cacuia
Média:  916.6667

Bairro:  Caju
Média:  850.0

Bairro:  Camorim
Média:  1735.2273

Bairro:  Campinho
Média:  1037.3333

Bairro:  Campo Grande
Média:  1267.7171

Bairro:  Cascadura
Média:  948.7097

Bairro:  Catete
Média:  2267.0625

Bairro:  Catumbi
Média:  1112.5

Bairro:  Cavalcanti
Média:  595.0

Bairro:  Centro
Média:  1254.7522

Bairro:  Cidade Jardim
Média:  12000.0

Bairro:  Cidade Nova
Média:  1471.4286

Bairro:  Cocotá
Média:  1883.3333

Bairro:  Coelho Neto
Média:  700.0

Bairro:  Colégio
Média:  885.0

Bairro:  Copacabana
Média:  4126.677

Bairro:  Cordovil
Média:  905.5556

Bairro:  Cosme Velho
Média:  5343.5484

Bairro:  Cosmos
Média:  658.3333

Bairro:  Curicica
Média:  1514.5658

Bairro:  Del Castilho
Média:  1261.3043

Bairro:  Encantado
Média:  1050.0

Bairro:  Engenho Novo
Média:  1035.8252

Bairro:  Engenho da Rainha
Média:  883.5714

Bairro:  Engenho de Dentro
Média:  1166.3514

Bairro:  Estácio
Média:  1233.913

Bairro:  Flamengo
Média:  4113.5266

Bairro:  Freguesia (Ilha do Governador)
Média:  1720.0

Bairro:  Freguesia (Jacarepaguá)
Média:  4966.6667

Bairro:  Fátima
Média:  956.6667

Bairro:  Gamboa
Média:  1116.6667

Bairro:  Gardênia Azul
Média:  761.1111

Bairro:  Glória
Média:  2467.2897

Bairro:  Grajaú
Média:  2038.6207

Bairro:  Guadalupe
Média:  700.0

Bairro:  Guaratiba
Média:  1232.2581

Bairro:  Gávea
Média:  6563.6884

Bairro:  Higienópolis
Média:  1006.25

Bairro:  Honório Gurgel
Média:  628.5714

Bairro:  Humaitá
Média:  3802.3101

Bairro:  Icaraí
Média:  2393.75

Bairro:  Ilha do Governador
Média:  1728.0

Bairro:  Inhaúma
Média:  821.4286

Bairro:  Inhoaíba
Média:  725.0

Bairro:  Ipanema
Média:  9352.0011

Bairro:  Irajá
Média:  1096.0127

Bairro:  Itanhangá
Média:  9341.2698

Bairro:  Jabour
Média:  723.3333

Bairro:  Jacarepaguá
Média:  2046.9878

Bairro:  Jacaré
Média:  1200.0

Bairro:  Jardim América
Média:  714.2857

Bairro:  Jardim Botânico
Média:  8722.3574

Bairro:  Jardim Carioca
Média:  2211.1111

Bairro:  Jardim Guanabara
Média:  2124.6875

Bairro:  Jardim Oceânico
Média:  7626.087

Bairro:  Jardim Sulacap
Média:  1176.6667

Bairro:  Joá
Média:  16773.4783

Bairro:  Lagoa
Média:  8147.0758

Bairro:  Lapa
Média:  1488.7778

Bairro:  Laranjeiras
Média:  3555.2776

Bairro:  Largo do Machado
Média:  1880.0

Bairro:  Leblon
Média:  8746.345

Bairro:  Leme
Média:  3944.7598

Bairro:  Lins de Vasconcelos
Média:  1086.1702

Bairro:  Madureira
Média:  1017.6596

Bairro:  Magalhães Bastos
Média:  640.0

Bairro:  Maracanã
Média:  1945.4961

Bairro:  Marechal Hermes
Média:  844.4444

Bairro:  Maria da Graça
Média:  1073.3333

Bairro:  Moneró
Média:  1900.0

Bairro:  Méier
Média:  1355.8745

Bairro:  Olaria
Média:  1016.5625

Bairro:  Oswaldo Cruz
Média:  823.8889

Bairro:  Paciência
Média:  580.0

Bairro:  Padre Miguel
Média:  786.25

Bairro:  Paquetá
Média:  10550.0

Bairro:  Parada de Lucas
Média:  1062.5

Bairro:  Parque Anchieta
Média:  1287.5

Bairro:  Pavuna
Média:  648.9474

Bairro:  Pechincha
Média:  1357.4257

Bairro:  Pedra de Guaratiba
Média:  1082.1053

Bairro:  Penha
Média:  1023.3333

Bairro:  Penha Circular
Média:  1160.0

Bairro:  Península
Média:  7061.5385

Bairro:  Piedade
Média:  956.5385

Bairro:  Pilares
Média:  1077.5

Bairro:  Pitangueiras
Média:  2725.0

Bairro:  Portuguesa
Média:  1272.7273

Bairro:  Praia da Bandeira
Média:  1300.0

Bairro:  Praça Seca
Média:  998.4146

Bairro:  Praça da Bandeira
Média:  1358.7234

Bairro:  Quintino Bocaiúva
Média:  924.6667

Bairro:  Ramos
Média:  958.0

Bairro:  Realengo
Média:  908.3333

Bairro:  Recreio dos Bandeirantes
Média:  3736.6131

Bairro:  Riachuelo
Média:  1143.9024

Bairro:  Ribeira
Média:  1420.0

Bairro:  Rio Comprido
Média:  1610.2405

Bairro:  Rio da Prata
Média:  1300.0

Bairro:  Rocha
Média:  1086.8421

Bairro:  Rocha Miranda
Média:  877.0

Bairro:  Sampaio
Média:  937.5

Bairro:  Santa Cruz
Média:  734.2857

Bairro:  Santa Teresa
Média:  2713.3333

Bairro:  Santo Cristo
Média:  1225.0

Bairro:  Santíssimo
Média:  756.25

Bairro:  Saúde
Média:  950.0

Bairro:  Senador Camará
Média:  600.0

Bairro:  Senador Vasconcelos
Média:  867.3529

Bairro:  São Conrado
Média:  8780.888

Bairro:  São Cristóvão
Média:  1391.7188

Bairro:  São Francisco Xavier
Média:  1237.2414

Bairro:  Tanque
Média:  1335.7143

Bairro:  Taquara
Média:  1642.1404

Bairro:  Tauá
Média:  1340.0

Bairro:  Tijuca
Média:  2043.52

Bairro:  Todos os Santos
Média:  1243.0769

Bairro:  Tomás Coelho
Média:  737.0

Bairro:  Turiaçu
Média:  700.0

Bairro:  Urca
Média:  7925.9589

Bairro:  Usina
Média:  1520.0

Bairro:  Vargem Grande
Média:  3358.1667

Bairro:  Vargem Pequena
Média:  2703.4808

Bairro:  Vaz Lobo
Média:  845.0

Bairro:  Vicente de Carvalho
Média:  1075.7143

Bairro:  Vidigal
Média:  2600.0

Bairro:  Vigário Geral
Média:  970.0

Bairro:  Vila Isabel
Média:  1560.8333

Bairro:  Vila Kosmos
Média:  1311.8182

Bairro:  Vila Militar
Média:  500.0

Bairro:  Vila Valqueire
Média:  1769.5833

Bairro:  Vila da Penha
Média:  1260.5769

Bairro:  Vista Alegre
Média:  1114.375

Bairro:  Zumbi
Média:  2150.0

Bairro:  Água Santa
Média:  861.1111

In [27]:
grupo_bairros[['Valor']].mean().round(4).head()

                       Valor
Bairro
Abolição           1195.3333
Alto da Boa Vista  3966.6667
Anchieta            875.0000
Andaraí            1464.7113
Anil               2048.8732

# Estatística Descritivas

In [28]:
grupo_bairros['Valor'].describe().round(2).head()

,count,mean,std,min,25%,50%,75%,max
Bairro,,,,,,,,
Abolição,15.0,1195.33,425.32,800.0,900.0,1180.0,1200.0,2300.0
Alto da Boa Vista,6.0,3966.67,5513.59,600.0,1150.0,1725.0,3275.0,15000.0
Anchieta,4.0,875.00,132.29,700.0,812.5,900.0,962.5,1000.0
Andaraí,97.0,1464.71,408.11,700.0,1200.0,1400.0,1650.0,2950.0
Anil,71.0,2048.87,1523.97,300.0,1100.0,1500.0,2675.0,7000.0

In [29]:
grupo_bairros['Valor'].aggregate(['min', 'max']).rename(columns={'min':'Mínimo','max':'Máximo'})

                       Mínimo     Máximo
Bairro
Abolição                800.0     2300.0
Alto da Boa Vista       600.0    15000.0
Anchieta                700.0     1000.0
Andaraí                 700.0     2950.0
Anil                    300.0     7000.0
Arpoador               4200.0    30000.0
Bancários              1300.0     2800.0
Bangu                   400.0     1650.0
Barra da Tijuca         800.0   600000.0
Barra de Guaratiba     2200.0     8000.0
Benfica                 790.0     1200.0
Bento Ribeiro           480.0     2200.0
Bonsucesso              600.0     4500.0
Botafogo                700.0  4500000.0
Braz de Pina            450.0     2300.0
Cachambi                600.0     2800.0
Cachamorra             3000.0     3000.0
Cacuia                  800.0     1050.0
Caju                    850.0      850.0
Camorim                 800.0     6000.0
Campinho                650.0     1700.0
Campo Grande            400.0    12000.0
Cascadura               650.0     1500.0
Catete                  700.0    15000.0
Catumbi                 650.0     1400.0
Cavalcanti              590.0      600.0
Centro                  400.0    12000.0
Cidade Jardim         12000.0    12000.0
Cidade Nova             800.0     2200.0
Cocotá                  700.0     4000.0
...                       ...        ...
Santíssimo              650.0      900.0
Saúde                   600.0     1300.0
Senador Camará          600.0      600.0
Senador Vasconcelos     500.0     2495.0
São Conrado            1400.0    45000.0
São Cristóvão           530.0     2500.0
São Francisco Xavier    700.0     2000.0
Tanque                  600.0     2500.0
Taquara                 500.0    10000.0
Tauá                    870.0     2000.0
Tijuca                  750.0    45000.0
Todos os Santos         800.0     1800.0
Tomás Coelho            650.0      900.0
Turiaçu                 600.0      900.0
Urca                   1200.0    35000.0
Usina                  1100.0     1900.0
Vargem Grande           800.0    20000.0
Vargem Pequena          850.0    17000.0
Vaz Lobo                400.0     1500.0
Vicente de Carvalho     500.0     2500.0
Vidigal                1300.0     4500.0
Vigário Geral           550.0     1500.0
Vila Isabel             700.0     4500.0
Vila Kosmos             850.0     2300.0
Vila Militar            500.0      500.0
Vila Valqueire          800.0    16000.0
Vila da Penha           450.0     4500.0
Vista Alegre            700.0     1400.0
Zumbi                  1600.0     2700.0
Água Santa              600.0     1200.0

[152 rows x 2 columns]

In [52]:
grupo_bairros['Valor'].aggregate(['min','max','sum']).rename(columns={'min':'Mínimo','max':'Máximo'})

                       Mínimo     Máximo         sum
Bairro
Abolição                800.0     2300.0     17930.0
Alto da Boa Vista       600.0    15000.0     23800.0
Anchieta                700.0     1000.0      3500.0
Andaraí                 700.0     2950.0    142077.0
Anil                    300.0     7000.0    145470.0
Arpoador               4200.0    30000.0    155087.0
Bancários              1300.0     2800.0      7300.0
Bangu                   400.0     1650.0     20320.0
Barra da Tijuca         800.0   600000.0  27309683.0
Barra de Guaratiba     2200.0     8000.0     22200.0
Benfica                 790.0     1200.0      4980.0
Bento Ribeiro           480.0     2200.0     23710.0
Bonsucesso              600.0     4500.0     72330.0
Botafogo                700.0  4500000.0   7675266.0
Braz de Pina            450.0     2300.0     22300.0
Cachambi                600.0     2800.0    152747.0
Cachamorra             3000.0     3000.0      3000.0
Cacuia                  800.0     1050.0      2750.0
Caju                    850.0      850.0       850.0
Camorim                 800.0     6000.0     76350.0
Campinho                650.0     1700.0     15560.0
Campo Grande            400.0    12000.0    569205.0
Cascadura               650.0     1500.0     29410.0
Catete                  700.0    15000.0    362730.0
Catumbi                 650.0     1400.0      8900.0
Cavalcanti              590.0      600.0      1190.0
Centro                  400.0    12000.0    430380.0
Cidade Jardim         12000.0    12000.0     12000.0
Cidade Nova             800.0     2200.0     10300.0
Cocotá                  700.0     4000.0      5650.0
...                       ...        ...         ...
Santíssimo              650.0      900.0      6050.0
Saúde                   600.0     1300.0      1900.0
Senador Camará          600.0      600.0       600.0
Senador Vasconcelos     500.0     2495.0     14745.0
São Conrado            1400.0    45000.0   2274250.0
São Cristóvão           530.0     2500.0     89070.0
São Francisco Xavier    700.0     2000.0     35880.0
Tanque                  600.0     2500.0     37400.0
Taquara                 500.0    10000.0    280806.0
Tauá                    870.0     2000.0     10720.0
Tijuca                  750.0    45000.0   2247872.0
Todos os Santos         800.0     1800.0     64640.0
Tomás Coelho            650.0      900.0      7370.0
Turiaçu                 600.0      900.0      3500.0
Urca                   1200.0    35000.0    578595.0
Usina                  1100.0     1900.0      7600.0
Vargem Grande           800.0    20000.0    201490.0
Vargem Pequena          850.0    17000.0    140581.0
Vaz Lobo                400.0     1500.0     21970.0
Vicente de Carvalho     500.0     2500.0     15060.0
Vidigal                1300.0     4500.0     10400.0
Vigário Geral           550.0     1500.0      4850.0
Vila Isabel             700.0     4500.0    468250.0
Vila Kosmos             850.0     2300.0     14430.0
Vila Militar            500.0      500.0      1000.0
Vila Valqueire          800.0    16000.0     84940.0
Vila da Penha           450.0     4500.0    131100.0
Vista Alegre            700.0     1400.0     17830.0
Zumbi                  1600.0     2700.0      4300.0
Água Santa              600.0     1200.0      7750.0

[152 rows x 3 columns]

In [53]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.rc('figure', figsize=(20, 10))

In [58]:
grupo_bairros['Valor'].std().plot.bar(color='blue')

NameError: name '_converter' is not defined